name = "art"
uuid = "9c34a329-d030-4394-b810-a016e660986c"
authors = ["flyjgh <doctorzwei@gmail.com>"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
